FROM kitematic/hello-world-nginx

#RUN \
#  mkdir -p /website_files/js &&\
#  mkdir -p /website_files/meta &&\
#  mkdir -p /website_files/style

#COPY ./favicon.ico /website_files/favicon.ico
#COPY ./index.html /website_files/index.html
#COPY ./.jshintrc /website_files/.jshintrc
#COPY ./Rakefile /website_files/Rakefile
#COPY ./README.md /website_files/README.md
#COPY ./LICENSE.txt /website_files/LICENSE.txt
#COPY ./js/animframe_polyfill.js /website_files/js/animframe_polyfill.js
#COPY ./js/application.js /website_files/js/application.js
#COPY ./js/bind_polyfill.js /website_files/js/bind_polyfill.js
#COPY ./js/classlist_polyfill.js /website_files/js/classlist_polyfill.js
#COPY ./js/game_manager.js /website_files/js/game_manager.js
#COPY ./js/grid.js /website_files/js/grid.js
#COPY ./js/html_actuator.js /website_files/js/html_actuator.js
#COPY ./js/keyboard_input_manager.js /website_files/js/keyboard_input_manager.js
#COPY ./js/local_storage_manager.js /website_files/js/local_storage_manager.js
#COPY ./js/tile.js /website_files/js/tile.js
#COPY ./meta/apple-touch-icon.png /website_files/meta/apple-touch-icon.png
#COPY ./meta/apple-touch-startup-image-640x1096.png /website_files/meta/apple-touch-startup-image-640x1096.png
#COPY ./meta/apple-touch-startup-image-640x920.png /website_files/meta/apple-touch-startup-image-640x920.png
COPY ./ /website_files
#COPY ./ /website_files

EXPOSE 80
